export const products = [
  {
    id: 1,
    title: 'Eco-Friendly Water Bottle',
    image: 'https://picsum.photos/seed/1/300/400',
    price: 19.99,
    description: 'Reusable, BPA-free water bottle made from recycled materials.',
    category: 'Accessories',
  },
  {
    id: 2,
    title: 'Organic Cotton T-Shirt',
    image: 'https://picsum.photos/seed/2/400/300',
    price: 29.99,
    description: 'Soft, breathable t-shirt made from 100% organic cotton.',
    category: 'Clothing',
  },
  {
    id: 3,
    title: 'Bamboo Toothbrush',
    image: 'https://picsum.photos/seed/3/500/500',
    price: 4.99,
    description: 'Biodegradable toothbrush with bamboo handle.',
    category: 'Personal Care',
  },
  {
    id: 4,
    title: 'Solar Power Bank',
    image: 'https://picsum.photos/seed/4/350/600',
    price: 39.99,
    description: 'Portable power bank charged by solar energy.',
    category: 'Electronics',
  },
  {
    id: 5,
    title: 'Reusable Shopping Bag',
    image: 'https://picsum.photos/seed/5/600/350',
    price: 9.99,
    description: 'Durable, foldable shopping bag made from recycled plastic.',
    category: 'Accessories',
  },
  {
    id: 6,
    title: 'Compost Bin',
    image: 'https://picsum.photos/seed/6/400/500',
    price: 49.99,
    description: 'Kitchen compost bin for easy food waste recycling.',
    category: 'Home',
  },
];
